# title: SuperSIM Website
email: olivia.chen@ieee.org
description: >-
  SuperSIM: A Benchmarking Framework for Superconductor-Based Neural Networks.
  This website provides information about research, tools, publications, and the team behind SuperSIM.
baseurl: "/SuperSIM-Website" # Leave empty for GitHub Pages
url: "https://cryo-lab.github.io/" # Change this if deploying elsewhere
twitter_username: ""
github_username: cryo-lab

# Theme and Plugins
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections (For Organizing Pages)
collections:
  pages:
    output: true
    permalink: /:path/

# Navigation Settings (Optional for Theme Compatibility)
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Tools
    url: /tools/
  - title: Publications
    url: /publications/
  - title: Team
    url: /team/
  - title: Contact
    url: /contact/

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Build Settings
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
